<?php
// //define('RESOURCE_NOT_FOUND', 1);
// define('INVALID_REQUEST_BODY', 3);
// define('INVALID_FIELDS', 2);
// define('ACCOUNT_CREATED', 4);
// define('INVALID_DATATYPES', 5);
// define('EMPTY_FIELDS', 6);
define('FILTER_VALIDATE_STRING', 7);
define('FILTER_VALIDATE_DATE', 8);
define('ACTIVE_USER', 2);
define('SUSPENDED_USER', 3);
define('ADMIN_USER', 1);
// define('CONTACT_EXISTS', 7);
// define('TRIES_EXCEEDED', 8);
// define('CODE_REQUIRED', 9);
// define('INVALID_CODE', 10);
// define('NO_PENDING_DATA', 11);
// define('LOGIN_FAILED', 12);
// define('LOGGED_IN', 13);
// define('CODE_SENT', 14);
 const OK = 200;
     const CREATED = 201;
const REQUEST_ACCEPTED = 202;
  const NO_CONTENT = 204;
 const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const PAYMENT_REQUIRED = 402;
const RESOURCE_NOT_FOUND = 404;
const REQUEST_LIMIT_EXCEEDED = 429;
const INTERNAL_SERVER_ERROR = 520;
